# Generated by Django 5.0.1 on 2024-01-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('price', models.CharField(max_length=10, verbose_name='Цена')),
                ('term', models.DateTimeField(verbose_name='Срок изготовления')),
                ('image', models.ImageField(blank=True, upload_to='img/%Y/%m/%d')),
                ('compound', models.CharField(max_length=30, verbose_name='Состав')),
            ],
        ),
    ]
