# Generated by Django 5.0.1 on 2024-01-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.FloatField(default=1, max_length=20, verbose_name='Вес'),
            preserve_default=False,
        ),
    ]
